### ISSUE TITLE
Where are versions 1.1.0 and 1.2.0 in the git commit history?

### ISSUE THREAD

**Issue by feross** [euank/node-parse-numeric-range#11]
I see versions 1.1.0 and 1.2.0 published to npm but they are not in the git commit history. Can you update the code on github to match what is on npm?

**Comment by euank** [comment]
Good catch. Those two tags existed, but I hadn't pushed 1.2.0 to the master branch (i.e. I only ran `git push --tags`). I've pushed the v1.2.0 commit to the master branch, so it should show up now.

Those commits could also have been found via the [releases](https://github.com/euank/node-parse-numeric-range/releases) tab on github, where it links to the tag's specific commits.

Note that 1.1.0 remains orphaned from the master branch (but you can still find the tag / git commit corresponding to it) since I made this same mistake last time.

Thanks for the ping / heads up that I messed up pushing that branch :smiley:

**Comment by feross** [comment]
Awesome, thank you!
